![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. Many other data science packages, especially those that work with matrices, rely on it for its speed and utility.

# Objectives

- Use NumPy to create arrays and perform efficient operations with them
- Use NumPy's other mathematical tools relevant to data analysis

For numpy, the standard alias is `np`.

In [1]:
import numpy as np

> NumPy Stat Functions:  
np.mean() - mean  
np.median() - median  
MODE is statistics.mode()  
np.std() - standard dev  
np.var() - variance  
np.cov()[0][1]- covariance *how 2 variables change together*  
np.corrcoef[0][1] - corr coeff *shows strength and direction*

# NumPy Arrays

Python lists and NumPy arrays can both hold numbers. However, Python lists have limited functionality for mathematical operations. NumPy arrays make it easy and fast to do math with a collection of numbers.

In [2]:
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


Note that there is an [`array` class in base Python](https://docs.python.org/3/library/array.html), but we will not be using it. It is essentially a list constrained to one type (e.g. int).

In [3]:
import array
x = array.array('i',[1,2,3])
print(x)
print(type(x))

array('i', [1, 2, 3])
<class 'array.array'>


## Character Arrays

NumPy arrays can either hold strings or numbers, not both. There is a special `chararray` object you can use with strings.

In [4]:
names_list = ['Bob', 'John', 'Sally']

# Use numpy.array for numbers and numpy.char.array for strings.

names_array = np.char.array(['Bob', 'John', 'Sally'])

print(names_list)
print(names_array)
type(names_array)

['Bob', 'John', 'Sally']
['Bob' 'John' 'Sally']


numpy.chararray

In [5]:
# The character array has string-functionality that numeric
# arrays don't have.

names_array.endswith('b')

array([ True, False, False])

## Numeric Arrays

Let's make a list and an array of three numbers, and see how they function differently

In [6]:
numbers_list = [0, 5, 7]
numbers_array = np.array([0, 5, 7])

### Type

Numeric arrays are have the `ndarray` type, which is short for N-Dimensional Array.

In [7]:
print(type(numbers_list))
print(type(numbers_array))

<class 'list'>
<class 'numpy.ndarray'>


## Arithmetic Operations

Arithmetic operators (e.g. +, -, * and /) work according to mathematical principles for arrays, unlike with lists. These operations are done "element-wise".

In [8]:
# multiply the array by 3

numbers_array * 3

array([ 0, 15, 21])

In [9]:
# multiply the list by 3

numbers_list * 3

[0, 5, 7, 0, 5, 7, 0, 5, 7]

In [10]:
numbers_array + 20

array([20, 25, 27])

In [11]:
numbers_list + 20

TypeError: can only concatenate list (not "int") to list

### Speed

Below, you will find a piece of code we will use to compare the speed of operations on lists vs arrays.

In [12]:
size_of_vec = 1000

X = list(range(size_of_vec))
Y = list(range(size_of_vec))

In [13]:
%timeit [X[i] + Y[i] for i in range(size_of_vec)]

93.9 µs ± 989 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
X = np.array(range(size_of_vec))
Y = np.array(range(size_of_vec))

In [15]:
%timeit X + Y

764 ns ± 27.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Array Attributes and Methods

Type `numbers_list.` and then hit `TAB`. What options do you have?

In [16]:
numbers_list.

SyntaxError: invalid syntax (<ipython-input-16-d0684ed2a409>, line 1)

The names of standard Python list methods appear:

- `append(x)` (add x to the end of the list)
- `clear()` (delete all elements of the list)
- `copy()` (make a copy of the list)
- `count(x)` (return the number of instances of x in the list)
- `extend([x, y])` (add x and y to the end of the list)
- `index(x)` (return the position in the list of x)
- `insert(x, y)` (insert y into position x in the list)
- `pop(i=-1)` (remove and return the element at position i in the list)
- `remove(x)` (remove x from the list)
- `reverse()` (reverse the order of the elements of the list)
- `sort()` (sort the elements of the list)

Now type `numbers_array.` and then hit `TAB`. What options do you have?

In [17]:
numbers_array.

SyntaxError: invalid syntax (<ipython-input-17-0813ce451c3c>, line 1)

Turns out, there are a _bunch_ of new tools!

### Numeric Methods

- `max()` (return the greatest value in the array)

In [18]:
numbers_array.max()

7

- `mean()` (return the arithmetic mean of the array)

In [19]:
numbers_array.mean()

4.0

- `min()` (return the smallest value in the array)

In [20]:
numbers_array.min()

0

- `round()` (round each entry in the array to a specified number of decimal places)

In [21]:
np.array([9.5, 1.2, 6.3]).round()

array([10.,  1.,  6.])

- `std()` (return the standard deviation of the array)

In [22]:
numbers_array.std()

2.943920288775949

- `sum()` (return the sum of the array's elements)

In [23]:
numbers_array.sum()

12

### Boolean Methods

- `all()` (returns True iff bool(element) == True for all elements in the array)

In [24]:
numbers_array.all()

False

- `any()` (returns True iff bool(element) == True for some element in the array)

In [25]:
numbers_array.any()

True

# Multi-Dimensional Indexing

Arrays are especially powerful when dealing with numbers in multiple dimensions - for example, a datset with rows and columns. We will primarily work with such 2-dimensional arrays.

In [26]:
nums = np.array([[1, 2, 3], [4, 5, 6]])
print(nums)

[[1 2 3]
 [4 5 6]]


In [27]:
print(nums.shape)

(2, 3)


In [28]:
nums[0, 2]

3

This more efficient than `nums[0][2]`. Why?

In [29]:
%timeit nums[0, 2]

136 ns ± 1.26 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [30]:
%timeit nums[0][2]

263 ns ± 1.09 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### Slicing

Use a trailing comma or colon to [slice](https://numpy.org/doc/stable/reference/arrays.indexing.html) sections of an array

In [35]:
nums

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
nums[1]

array([4, 5, 6])

In [32]:
nums[1,]

array([4, 5, 6])

In [33]:
nums[1,:]

array([4, 5, 6])

In [34]:
nums[:,1]

array([2, 5])

### Reshaping

In [36]:
new = np.array([[1, 2, 3], [4, 5, 6]])
new

array([[1, 2, 3],
       [4, 5, 6]])

- `shape` (stores the dimension of the array)

In [37]:
new.shape

(2, 3)

- `ravel()` (reduce array to one dimension)

In [38]:
new.ravel()

array([1, 2, 3, 4, 5, 6])

- `reshape()` (return an array with the specified dimensions)

In [39]:
new.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

- `T` (stores the transpose of the array)

In [40]:
new.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# NumPy Functions

NumPy has a bunch of functions, besides array methods, that are helpful for working with arrays.

## Array Constructors

In [41]:
print(np.zeros(10))
print(np.ones(10))
print(np.arange(10, dtype=float))
print(np.linspace(0.1, 1, 10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### `np.concatenate()`

In [42]:
np.concatenate([[1, 2], [3, 4]])

array([1, 2, 3, 4])

## Filtering

In [43]:
data = np.array([10, 3, 4, 7, 6])

In [44]:
data < 5

array([False,  True,  True, False, False])

In [45]:
data[data < 5]

array([3, 4])

### `np.where()`

> np.where(condition, x, y)

In [46]:
np.where(data < 5, "Low", "High")

array(['High', 'Low', 'Low', 'High', 'High'], dtype='<U4')

### `np.select()`

> np.select([conditions], [choices], default='else')

In [47]:
conditions = [data < 5, data > 9]

choices = ['small', 'big!']

In [48]:
np.select(conditions, choices, default='other')

array(['big!', 'small', 'small', 'other', 'other'], dtype='<U5')

## Broadcasting

Two arrays can be combined with mathematical operations via [broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html).  

From the [docs](https://numpy.org/doc/stable/user/basics.broadcasting.html):

    When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions and works its way forward. **Two dimensions are compatible when
    - they are equal, or
    - one of them is 1**
    
Let's try to figure out what will happen in the operations below

In [49]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 100, 1000])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[  10  100 1000]


In [50]:
print(arr1.shape)
print(arr2.shape)

(2, 3)
(3,)


In [51]:
arr1 * arr2

array([[  10,  200, 3000],
       [  40,  500, 6000]])

In [52]:
arr3 = np.array([10, 100])
arr3.shape

(2,)

In [53]:
arr1 * arr3

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [54]:
arr4 = np.array([[10, 100]])
arr4.shape

(1, 2)

In [55]:
arr1 * arr4

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [56]:
arr5 = np.array([[10],[100]])
arr5.shape

(2, 1)

In [57]:
arr1 * arr5

array([[ 10,  20,  30],
       [400, 500, 600]])

# Other NumPy Tools

NumPy comes with an assortment of mathematical tools that can come in handy, separate from arrays.

## Trigonometry 

- `np.pi` for $\pi$

In [58]:
np.pi

3.141592653589793

- `np.sin()` for the sine function

In [59]:
np.sin(np.pi / 6)

0.49999999999999994

## Sequences


- `np.cumsum()` to calculate, recursively, the sum of sequence terms

In [60]:
np.cumsum([1, 4, 9, 16])

array([ 1,  5, 14, 30])

- `np.diff()` to calculate, recursively, the differences between sequence terms

In [61]:
np.diff([1, 4, 9, 16])

array([3, 5, 7])

## Logarithms
- `np.exp()` for Euler's number with exponent

In [62]:
np.exp(2)

7.38905609893065

- `np.log()` for logarithms

In [63]:
np.log(10)

2.302585092994046

## np.nan

NaN stands for "not a number" - NumPy's `nan` class is a handy way of representing these.  These are very useful for representing missing data.

Since `np.nan` is is a float, we don't get errors when doing operations on arrays that have missing data. 

In [64]:
type(np.nan)

float

In [65]:
arr5 = np.array([1, 10, np.nan])

In [66]:
arr5.mean()

nan

Even though the array has a NaN, we don't get an error in calculating its mean. Moreover, we can do this:

> These methods disregard NaN values when calculating!

In [67]:
np.nansum(arr5) / len(arr5)

3.6666666666666665

Is the right measure of the mean? Well, maybe. But if not, we also have this:

In [68]:
np.nanmean(arr5)

5.5

## np.inf

Sometimes you will end up with values of infinity represented by `np.inf`, such as if you divide by zero. `np.inf` is a float, like `np.nan` is.

In [69]:
np.array([2])/np.array([0])

<ipython-input-69-f57fc9927d0a>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([2])/np.array([0])


array([inf])

In [70]:
type(np.inf)

float

In [71]:
np.isfinite(np.inf)

False

This can also be useful when handling edge cases in custom functions

In [72]:
def inv(x):
    return x**(-2)

In [73]:
inv(0)

ZeroDivisionError: 0.0 cannot be raised to a negative power

In [74]:
def inverse(x):
    if x == 0:
        val = np.inf
    else:
        val = x**(-2)
    return val

In [75]:
inverse(0)

inf