# On the Meaning and Use of Singular Value Decomposition

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

## Agenda

SWBAT:

- explain the notion of singular value decomposition;
- describe the relationship between SVD and eigendecomposition;
- describe the relationship between SVD and PCA.

## Eigendecomposition

Let's start with eigendecomposition. Remember PCA?

Any *non-defective* and *square* matrix $A$ has an eigendecomposition:

Non-defective you have as many equations as are unknowns

$\large A = Q\Lambda Q^{-1}$,

where:

- the columns of $Q$ are the eigenvectors of $A$, and
- $\Lambda$ is a diagonal matrix whose non-zero entries are the eigenvalues of $A$.
-The upsidedown V is capital lambda

Q is eigenvector (row) * Lamba (diagonal matrix) * Q-1 is flipped with eigenvect(column)

Eigendecompositions have *many* practical applications.

But since not all matrices are square, not all matrices have eigendecompositions.

## Singular Value Decomposition

If you multiply a matrix of by it's transpose, you are squaring it!

However, given a non-square matrix $R$, we can construct a square matrix by simply calculating $RR^T$ or $R^TR$.

(The 'T' superscript indicates that the relevant matrix is *transposed*, i.e. its rows and columns are switched. So for example the transpose of $\begin{bmatrix} 0 & 1 & 2 \\ 3 & 4 & 5 \\ 6 & 7 & 8 \end{bmatrix}$ is $\begin{bmatrix} 0 & 3 & 6 \\ 1 & 4 & 7 \\ 2 & 5 & 8 \end{bmatrix}$.)

Moreover, _any_ matrix $A$ has a ***singular value decomposition***, i.e. a factorization in the form:

$\large A = U\Sigma V^T$,

where

- $\Sigma$ is diagonal if square and otherwise "pseudo-diagonal" (a diagonal matrix sitting on top of zeroes) with real, non-negative entries; and
- $U$ and $V$ are orthogonal.

A matrix $Q$ is orthogonal if its columns are mutually orthogonal and normalized to lengths of 1. This guarantees that, for orthogonal $Q$, $Q^TQ = I$. Thus, $Q^T = Q^T(QQ^{-1}) = (Q^TQ)Q^{-1}$, so $Q^T = Q^{-1}$.

Note also that, if $V$ is orthogonal, then so is $V^{-1}$:

$(V^{-1})^T = (V^T)^T$ <br/>
$(V^{-1})^T = V$ <br/>
$(V^{-1})^T = (V^{-1})^{-1}$

Now (this text adapted from [Inderjit Dhillon]( http://www.cs.utexas.edu/users/inderjit/courses/dm2009/LinearAlgebraBackground.pdf)):

Using the singular value decomposition of $A$, we have:

$\large AA^T = U\Sigma V^T\times(U\Sigma V^T)^T$ <br/>
$\large AA^T = U\Sigma V^T\times V\Sigma^TU^T$ <br/>
$\large AA^T = U\Sigma I\Sigma U^T$ <br/>
$\large AA^T = U\Sigma^2U^T$ <br/>
Here we have an eigendecomposition of $AA^T$ in terms of the SVD of $A$!

In particular:

the eigenvectors of $AA^T$ are the columns of $U$; and <br/>
the eigenvalues of $AA^T$ are the squares of the singular values of $A$. <br/>

Similarly, $\large A^TA = V\Sigma^2V^T$.

And so:

the eigenvectors of $A^TA$ are the columns of $V$; and <br/>
the eigenvalues of $A^TA$ are the squares of the singular values of $A$.<br/>

Put another way: The singular values of A are the non-negative square roots of the eigenvalues of $AA^T$ or $A^TA$.

Again (see [this page](https://math.stackexchange.com/questions/2152751/why-does-the-eigenvalues-of-aat-are-the-squares-of-the-singular-values-of-a)):

Since: <br/> $\large AA^T = U\Sigma^2U^T$, <br/> we have that <br/> $\large AA^TU = U\Sigma^2$ (since $U$ is orthogonal), <br/> which says that $AA^T$ multiplied by a vector (let's choose $U_i$, a column of $U$) yields $U$ multiplied by a scalar, namely $\sigma^2_i$. I.e. the squares of the singular values of $A$ are the (non-zero) eigenvalues of $A^TA$ (or $AA^T$).

### Eigenvalues of $AA^T$ and $A^TA$
Why do $AA^T$ and $A^TA$ have the same eigenvalues?

Let $\lambda$ be a (non-zero) eigenvalue of $A^TA$.

Then:

$A^TAx = \lambda x$.

Now let $Ax = y$. So we have:

$A^Ty = \lambda x$. If we left-multiply by $A$, we have:

$AA^Ty = A\lambda x = \lambda Ax = \lambda y$, which is to say that $\lambda$ is an eigenvalue of $AA^T$.

(To show the reverse, just let $B = A^T$.)

For more, see [this post](https://math.stackexchange.com/questions/1087064/non-zero-eigenvalues-of-aat-and-ata).

### Diagonalization vs. SVD

This shows that the eigen- and the singular value decompositions are intimately related!

The SVD has many uses! Check out [this book chapter](https://www.cs.cmu.edu/~venkatg/teaching/CStheory-infoage/book-chapter-4.pdf) for details.

### SVD and Dimensionality Reduction

The SVD, much like PCA, can be used to reduce the dimensionality of your data.

Recall how PCA works: We start with an eigendecomposition of our covariance matrix. We then order our eigenvectors by the size of their corresponding eigenvalues. Eigenvectors with large eigenvalues explain more of the variance in our dataset, and so we define our principal components accordingly.

The situation is much the same with the SVD. The singular vectors that correspond to larger singular values capture more of the variance in our data. And, just as with PCA, we can often capture a large percentage of the variance by taking a relatively small number of singular vectors, throwing out the ones that correspond to small singular values. [Here](https://rpubs.com/Tanmay007/svd) is a good example of this process.

## SVD in Python

Let's show that the squares of the singular values of a non-square matrix $A$ are equal to the eigenvalues of $A^TA$ (or $AA^T$).

In [2]:
np.random.seed(42)
A = np.random.rand(5, 3)
A

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
# Using np.linalg.svd()

np.linalg.svd(A)

(array([[-0.5991048 , -0.38620771, -0.12988737, -0.68883081, -0.02363108],
        [-0.25170251,  0.32375656, -0.38389036,  0.13776803, -0.81576694],
        [-0.4495347 , -0.55516825,  0.01152904,  0.69900869,  0.03099514],
        [-0.51180949,  0.4814656 ,  0.71001691,  0.04057048,  0.0217244 ],
        [-0.33717783,  0.45387706, -0.57576083,  0.12756552,  0.57665694]]),
 array([1.99063285, 1.0096001 , 0.57767497]),
 array([[-0.52458829, -0.54271957, -0.65594405],
        [ 0.72866708, -0.6846751 , -0.01625695],
        [-0.44028559, -0.48649304,  0.75463443]]))

`np.linalg.svd()` returns a triple, unsurprisingly: The left singular vectors ("U"), the singular values, and the (transpose of the) right singular vectors ("V").

We can re-create A by multiplying these components together. But we'll first have to turn the array of singular values into $\Sigma$, so we'll use `np.diag()` together with `np.vstack()`.

In [4]:
u, s, vT = np.linalg.svd(A)

In [5]:
sigma = np.vstack([np.diag(s), [[0, 0, 0], [0, 0, 0]]])

In [6]:
sigma

array([[1.99063285, 0.        , 0.        ],
       [0.        , 1.0096001 , 0.        ],
       [0.        , 0.        , 0.57767497],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])

In [7]:
# This should reproduce the matrix A

u.dot(sigma).dot(vT)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

Now let's look at the eigendecomposition of $AA^T$.

In [8]:
np.linalg.eig(A.dot(A.T))

(array([ 3.96261914e+00,  1.01929237e+00,  3.33708373e-01, -3.85173654e-17,
         6.67933316e-17]),
 array([[-0.5991048 , -0.38620771,  0.12988737, -0.56579353,  0.31590997],
        [-0.25170251,  0.32375656,  0.38389036, -0.37821855, -0.77909222],
        [-0.4495347 , -0.55516825, -0.01152904,  0.57835455, -0.31445698],
        [-0.51180949,  0.4814656 , -0.71001691,  0.0455007 , -0.00086544],
        [-0.33717783,  0.45387706,  0.57576083,  0.44750879,  0.44083133]]))

Let's extract the eigenvalues.

In [9]:
np.linalg.eig(A.dot(A.T))[0]

array([ 3.96261914e+00,  1.01929237e+00,  3.33708373e-01, -3.85173654e-17,
        6.67933316e-17])

The last two eigenvalues are really equal to *zero*, which of course can often confuse computers. Squaring the singular values of $A$ should yield the same list (without the zeroes):

In [10]:
np.linalg.svd(A)[1]**2

array([3.96261914, 1.01929237, 0.33370837])

>PCA take covariance and find the eigenvectors. Basically multiplying by it's transpose.

## Relation to PCA

We'll start by **centering** the matrix, i.e. subtracting the mean of the relevant column from each entry:

In [11]:
centered_A = np.vstack([A[:, col] - A.mean(axis=0)[col] for col in range(3)]).T

In [12]:
centered_A

array([[-0.13981937,  0.50954777,  0.20382628],
       [ 0.084299  , -0.2851479 , -0.37217314],
       [-0.45627587,  0.42500961,  0.07294735],
       [ 0.19371309, -0.42058205,  0.44174219],
       [ 0.31808315, -0.22882743, -0.34634269]])

The column sums should now be 0:

In [13]:
centered_A.sum(axis=0)

array([3.33066907e-16, 5.55111512e-16, 3.33066907e-16])

The covariance matrix of a centered matrix $A$ is equal to $A^TA/(n-1)$, where $n$ is the number of rows of $A$. See [this helpful post](https://stats.stackexchange.com/questions/134282/relationship-between-svd-and-pca-how-to-use-svd-to-perform-pca).

In [14]:
np.allclose(np.cov(centered_A.T), centered_A.T.dot(centered_A) / 4)

True

SVD of centered matrix:

In [15]:
u_c, s_c, vT_c = np.linalg.svd(centered_A)

PCA begins by diagonalizing the covariance matrix. And with these matrices generated by the SVD we can reproduce the covariance matrix of $A_{centered}$:

In [16]:
vT_c.T.dot(np.diag(s_c)**2).dot(vT_c) / 4

array([[ 0.09338628, -0.11086559, -0.02943783],
       [-0.11086559,  0.18770817,  0.0336127 ],
       [-0.02943783,  0.0336127 ,  0.12511719]])

In [17]:
np.cov(centered_A.T)

array([[ 0.09338628, -0.11086559, -0.02943783],
       [-0.11086559,  0.18770817,  0.0336127 ],
       [-0.02943783,  0.0336127 ,  0.12511719]])

##  Least-Squares Problem

The singular value decomposition can be used to solve a least-squares problem quickly. Let's create such a problem.

### Comparison to the matrix-vector equation, $M\vec{x} = \vec{b}$

Suppose we have an exact equation, $M\vec{x} = \vec{b}$.

In that case $M$ is square, and the solution to the equation is $x = M^{-1}b$.

In [18]:
np.random.seed(43)
M = np.random.rand(5, 5)
b = np.random.rand(5, 1)

In [19]:
b

array([[0.66972465],
       [0.08250005],
       [0.89709858],
       [0.2980035 ],
       [0.26230482]])

In [20]:
x = np.linalg.inv(M).dot(b)

In [21]:
# Reproducing the vector b

M.dot(x)

array([[0.66972465],
       [0.08250005],
       [0.89709858],
       [0.2980035 ],
       [0.26230482]])

### Optimization Problem

But of course the typical DS situation is that we have not an exact equation to solve but rather an optimization to perform. So let's now imagine that $A$ has more rows than columns.

If we need some warm and fuzzy familiarity, we could throw this all into a DataFrame:

In [22]:
pd.DataFrame(np.hstack([A, b]),
             columns=['pred1', 'pred2', 'pred3', 'target'])

pred1     pred2     pred3    target
0  0.374540  0.950714  0.731994  0.669725
1  0.598658  0.156019  0.155995  0.082500
2  0.058084  0.866176  0.601115  0.897099
3  0.708073  0.020584  0.969910  0.298004
4  0.832443  0.212339  0.181825  0.262305

Treating the columns of $A$ as our predictors and $b$ as our target, the answer to this least-squares problem turns out to be $A^+\vec{b}$, where $A^+$ is the *pseudo-inverse* of $A$. The formula for the pseudo-inverse if $(A^TA)^{-1}A^T$, and the idea behind it is to generalize the notion of an inverse to non-square matrices. The pseudo-inverse reduces to the inverse in the case of square matrices.

In [23]:
mat = np.random.rand(100, 100)
np.allclose(np.linalg.inv(mat), np.linalg.pinv(mat))

True

If we have $A = U\Sigma V^T$, then $A^+ = V\Sigma^+U^T$. Numpy has a pseudo-inverse function, `np.linalg.pinv()`, which we could use directly, rather than first constructing the SVD. But because the decomposed equation involves only the pseudo-inverse of a (pseudo-) diagonal matrix, the SVD route can be much *faster*. **This is the real point of using the SVD in calculating least-squares solutions.**

See [this site](https://math.stackexchange.com/questions/974193/why-does-svd-provide-the-least-squares-and-least-norm-solution-to-a-x-b) for a proof of the least-squares solution. For more on the pseudo-inverse, see [here](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse).

In [24]:
# Let's calculate the least-squares solution using our SVD components:

vT.T.dot(np.linalg.pinv(sigma)).dot(u.T).dot(b)

array([[-0.01999533],
       [ 0.64792212],
       [ 0.29648717]])

In [25]:
# Checking against sklearn's LinearRegression():

LinearRegression(fit_intercept=False).fit(A, b).coef_

array([[-0.01999533,  0.64792212,  0.29648717]])

In fact, `LinearRegression()` uses SVD under the hood!

### Timings

In [26]:
%timeit vT.T.dot(np.linalg.pinv(sigma)).dot(u.T).dot(b)

50.3 µs ± 1.36 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [27]:
%timeit LinearRegression(fit_intercept=False).fit(A, b).coef_

237 µs ± 9.37 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [28]:
%timeit np.linalg.pinv(A).dot(b)

54 µs ± 3.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


For our small sample matrix, `sklearn`'s version actually takes longer. But let's try a much larger matrix!

In [29]:
np.random.seed(42)
X = np.random.rand(10000, 100)
target = np.random.rand(10000, 1)

In [30]:
%timeit np.linalg.pinv(X).dot(target)

43.4 ms ± 1.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
%timeit LinearRegression(fit_intercept=False).fit(X, target).coef_

26.1 ms ± 905 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Going through the SVD (as `sklearn`'s model-fitting procedure does) makes noticeable savings in time here.

## Further Resources

- The [MovieLens](https://grouplens.org/datasets/movielens/) datset(s).
- [This article](https://analyticsindiamag.com/singular-value-decomposition-svd-application-recommender-system/) that illustrates the SVD in a recommender system.
- The [`surprise`](https://surprise.readthedocs.io/en/stable/) library, which you'll see in the Learn labs.