<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Objectives" data-toc-modified-id="Objectives-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Objectives</a></span></li><li><span><a href="#Aggregating:-Averaging,-Bagging,-and-Random-Forests" data-toc-modified-id="Aggregating:-Averaging,-Bagging,-and-Random-Forests-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Aggregating: Averaging, Bagging, and Random Forests</a></span><ul class="toc-item"><li><span><a href="#Data-Preparation-for-Examples" data-toc-modified-id="Data-Preparation-for-Examples-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Data Preparation for Examples</a></span></li></ul></li><li><span><a href="#Averaging" data-toc-modified-id="Averaging-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Averaging</a></span><ul class="toc-item"><li><span><a href="#Model-1---Linear-Regression" data-toc-modified-id="Model-1---Linear-Regression-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Model 1 - Linear Regression</a></span></li><li><span><a href="#Model-2---KNN" data-toc-modified-id="Model-2---KNN-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Model 2 - KNN</a></span></li><li><span><a href="#Model-3---Decision-Tree" data-toc-modified-id="Model-3---Decision-Tree-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Model 3 - Decision Tree</a></span></li><li><span><a href="#Averaging-the-Models" data-toc-modified-id="Averaging-the-Models-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Averaging the Models</a></span><ul class="toc-item"><li><span><a href="#From-Scratch" data-toc-modified-id="From-Scratch-3.4.1"><span class="toc-item-num">3.4.1&nbsp;&nbsp;</span>From Scratch</a></span></li><li><span><a href="#Building-a-VotingClassifier" data-toc-modified-id="Building-a-VotingClassifier-3.4.2"><span class="toc-item-num">3.4.2&nbsp;&nbsp;</span>Building a <code>VotingClassifier</code></a></span></li><li><span><a href="#Weighted-Averaging" data-toc-modified-id="Weighted-Averaging-3.4.3"><span class="toc-item-num">3.4.3&nbsp;&nbsp;</span>Weighted Averaging</a></span><ul class="toc-item"><li><span><a href="#Weighted-Averaging-with-the-VotingClassifier" data-toc-modified-id="Weighted-Averaging-with-the-VotingClassifier-3.4.3.1"><span class="toc-item-num">3.4.3.1&nbsp;&nbsp;</span>Weighted Averaging with the VotingClassifier</a></span></li></ul></li></ul></li></ul></li><li><span><a href="#Bagging" data-toc-modified-id="Bagging-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Bagging</a></span><ul class="toc-item"><li><span><a href="#Bagging-Algorithm" data-toc-modified-id="Bagging-Algorithm-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Bagging Algorithm</a></span></li><li><span><a href="#Back-to-the-Example-Data" data-toc-modified-id="Back-to-the-Example-Data-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Back to the Example Data</a></span><ul class="toc-item"><li><span><a href="#Change-the-base-estimator" data-toc-modified-id="Change-the-base-estimator-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>Change the base estimator</a></span></li></ul></li></ul></li><li><span><a href="#Fitting-a-Random-Forest" data-toc-modified-id="Fitting-a-Random-Forest-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Fitting a Random Forest</a></span><ul class="toc-item"><li><span><a href="#An-Aside-Story---Bananas-🍌" data-toc-modified-id="An-Aside-Story---Bananas-🍌-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>An Aside Story - Bananas 🍌</a></span></li><li><span><a href="#The-Goods-&amp;-The-Bads" data-toc-modified-id="The-Goods-&amp;-The-Bads-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>The Goods &amp; The Bads</a></span><ul class="toc-item"><li><span><a href="#Breed-variety-of-trees" data-toc-modified-id="Breed-variety-of-trees-5.2.1"><span class="toc-item-num">5.2.1&nbsp;&nbsp;</span>Breed variety of trees</a></span><ul class="toc-item"><li><span><a href="#Steps:" data-toc-modified-id="Steps:-5.2.1.1"><span class="toc-item-num">5.2.1.1&nbsp;&nbsp;</span>Steps:</a></span></li></ul></li></ul></li><li><span><a href="#Back-to-the-Example-Data" data-toc-modified-id="Back-to-the-Example-Data-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Back to the Example Data</a></span></li><li><span><a href="#Cool-Features-of-Random-Forests" data-toc-modified-id="Cool-Features-of-Random-Forests-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Cool Features of Random Forests</a></span><ul class="toc-item"><li><span><a href="#Investigate-Your-Forest-🌲🌲👀🌲🌲" data-toc-modified-id="Investigate-Your-Forest-🌲🌲👀🌲🌲-5.4.1"><span class="toc-item-num">5.4.1&nbsp;&nbsp;</span>Investigate Your Forest 🌲🌲👀🌲🌲</a></span></li><li><span><a href="#Feature-Importance" data-toc-modified-id="Feature-Importance-5.4.2"><span class="toc-item-num">5.4.2&nbsp;&nbsp;</span>Feature Importance</a></span></li></ul></li><li><span><a href="#Extremely-Randomized-Trees-(Extra-Trees)" data-toc-modified-id="Extremely-Randomized-Trees-(Extra-Trees)-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>Extremely Randomized Trees (Extra Trees)</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV,\
cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier,\
ExtraTreesClassifier, VotingClassifier
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder

# Objectives

SWBAT:

- Use `sklearn` to build voting models
- Describe the algorithm of bagging
- Describe the differences among simple bagging, random forest, and extra trees algorithms
- Implement bagging models in `sklearn`

# Aggregating: Averaging, Bagging, and Random Forests

We can imagine training different models (maybe with different conditions) and then having them "vote" on what they think is best.

## Data Preparation for Examples

> Let's prepare some data to do some examples

In [2]:
df = pd.read_csv('data/salaries.csv')
df.head()

Age  Education         Occupation   Relationship     Sex Target
0   39  Bachelors       Adm-clerical  Not-in-family    Male  <=50K
1   50  Bachelors    Exec-managerial        Husband    Male  <=50K
2   38    HS-grad  Handlers-cleaners  Not-in-family    Male  <=50K
3   53       11th  Handlers-cleaners        Husband    Male  <=50K
4   28  Bachelors     Prof-specialty           Wife  Female  <=50K

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Age           32561 non-null  int64 
 1   Education     32561 non-null  object
 2   Occupation    32561 non-null  object
 3   Relationship  32561 non-null  object
 4   Sex           32561 non-null  object
 5   Target        32561 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.5+ MB


In [4]:
df.isna().sum().sum()

0

In [5]:
# Convert Target to 0 or 1
df['Target'] = df['Target'] == '>50K'

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('Target',axis=1), df['Target'], random_state=42)

In [7]:
ohe = OneHotEncoder(drop='first', sparse=False)
ohe.fit(X_train.select_dtypes('object'))

OneHotEncoder(drop='first', sparse=False)

In [8]:
X_tr_ohe = pd.DataFrame(ohe.transform(X_train.select_dtypes('object')),
                                  columns=ohe.get_feature_names(),
                                    index=X_train.index)

In [9]:
X_tr_ohe.head()

x0_11th  x0_12th  x0_1st-4th  x0_5th-6th  x0_7th-8th  x0_9th  \
29         0.0      0.0         0.0         0.0         0.0     0.0   
12181      0.0      0.0         0.0         0.0         0.0     0.0   
18114      1.0      0.0         0.0         0.0         0.0     0.0   
4278       0.0      0.0         0.0         0.0         0.0     0.0   
12050      0.0      0.0         0.0         0.0         0.0     0.0   

       x0_Assoc-acdm  x0_Assoc-voc  x0_Bachelors  x0_Doctorate  ...  \
29               0.0           0.0           0.0           0.0  ...   
12181            0.0           0.0           0.0           0.0  ...   
18114            0.0           0.0           0.0           0.0  ...   
4278             0.0           0.0           1.0           0.0  ...   
12050            0.0           0.0           1.0           0.0  ...   

       x1_Protective-serv  x1_Sales  x1_Tech-support  x1_Transport-moving  \
29                    0.0       0.0              0.0                  0.0   
12181                 0.0       0.0              0.0                  0.0   
18114                 0.0       0.0              0.0                  0.0   
4278                  0.0       0.0              0.0                  0.0   
12050                 0.0       1.0              0.0                  0.0   

       x2_Not-in-family  x2_Other-relative  x2_Own-child  x2_Unmarried  \
29                  0.0                0.0           0.0           0.0   
12181               0.0                0.0           0.0           0.0   
18114               0.0                0.0           0.0           0.0   
4278                0.0                0.0           0.0           1.0   
12050               1.0                0.0           0.0           0.0   

       x2_Wife  x3_Male  
29         0.0      1.0  
12181      0.0      1.0  
18114      0.0      1.0  
4278       0.0      1.0  
12050      0.0      0.0  

[5 rows x 35 columns]

In [10]:
X_te_ohe = pd.DataFrame(ohe.transform(X_test.select_dtypes('object')),
                                  columns=ohe.get_feature_names(),
                                    index=X_test.index)


In [11]:
X_te_ohe.head()

x0_11th  x0_12th  x0_1st-4th  x0_5th-6th  x0_7th-8th  x0_9th  \
14160      0.0      0.0         0.0         0.0         0.0     0.0   
27048      0.0      0.0         0.0         0.0         0.0     0.0   
28868      0.0      0.0         0.0         0.0         0.0     0.0   
5667       0.0      0.0         0.0         0.0         0.0     0.0   
7827       0.0      0.0         0.0         0.0         0.0     0.0   

       x0_Assoc-acdm  x0_Assoc-voc  x0_Bachelors  x0_Doctorate  ...  \
14160            0.0           0.0           0.0           0.0  ...   
27048            0.0           0.0           0.0           0.0  ...   
28868            0.0           0.0           1.0           0.0  ...   
5667             0.0           0.0           1.0           0.0  ...   
7827             0.0           0.0           0.0           0.0  ...   

       x1_Protective-serv  x1_Sales  x1_Tech-support  x1_Transport-moving  \
14160                 0.0       0.0              0.0                  0.0   
27048                 0.0       0.0              0.0                  0.0   
28868                 0.0       0.0              0.0                  0.0   
5667                  0.0       0.0              0.0                  0.0   
7827                  0.0       0.0              0.0                  0.0   

       x2_Not-in-family  x2_Other-relative  x2_Own-child  x2_Unmarried  \
14160               1.0                0.0           0.0           0.0   
27048               0.0                0.0           0.0           0.0   
28868               0.0                0.0           0.0           0.0   
5667                1.0                0.0           0.0           0.0   
7827                1.0                0.0           0.0           0.0   

       x2_Wife  x3_Male  
14160      0.0      0.0  
27048      1.0      0.0  
28868      0.0      1.0  
5667       0.0      0.0  
7827       0.0      1.0  

[5 rows x 35 columns]

# Averaging

> Each model uses the same data to train and then we "vote" to make a prediction

## Model 1 - Linear Regression

In [12]:
lr = LogisticRegression()

lr.fit(X_tr_ohe, y_train)

LogisticRegression()

In [13]:
scores = cross_val_score(estimator=lr, X=X_tr_ohe,
                        y=y_train, cv=5)
scores

array([0.81859132, 0.82903358, 0.82657658, 0.83108108, 0.82473382])

In [14]:
np.median(scores)

0.8265765765765766

In [15]:
lr.score(X_te_ohe, y_test)

0.8312246652745363

## Model 2 - KNN

In [16]:
knn = KNeighborsClassifier()

knn.fit(X_tr_ohe, y_train)

KNeighborsClassifier()

In [17]:
scores = cross_val_score(estimator=knn, X=X_tr_ohe,
                y=y_train, cv=5)
np.median(scores)

0.7905405405405406

In [18]:
knn.score(X_te_ohe, y_test)

0.77607173565901

>KNN takes a long time because it looks at every point and it's the making predictions part that is taking so long.

## Model 3 - Decision Tree

In [19]:
rt = DecisionTreeClassifier(random_state=42)

rt.fit(X_tr_ohe, y_train)

DecisionTreeClassifier(random_state=42)

In [20]:
scores = cross_val_score(estimator=rt, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.81613432, 0.82166257, 0.82104832, 0.82964783, 0.81981982])

In [21]:
np.median(scores)

0.821048321048321

In [22]:
rt.score(X_te_ohe, y_test)

0.8250829136469722

## Averaging the Models

### From Scratch

To build our simple averagaing meata-estimator, we'll just average the predictions of the three base estimators:

In [25]:
meta_preds = np.round(sum([lr.predict(X_te_ohe), knn.predict(X_te_ohe),
                  rt.predict(X_te_ohe)]) / 3)

Now we can evaluate our meta-estimator:

In [26]:
r2_score(y_test, meta_preds)

0.04818438168562922

### Building a `VotingClassifier`

> Of course there's a Scikit-Learn class for that

In [27]:
avg = VotingClassifier(estimators=[
    ('lr', lr),
    ('knn', knn),
    ('rt', rt)])
avg.fit(X_tr_ohe, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier()),
                             ('rt', DecisionTreeClassifier(random_state=42))])

In [28]:
scores = cross_val_score(estimator=avg, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.81756757, 0.82616708, 0.82289107, 0.83210483, 0.82289107])

In [29]:
np.median(scores)

0.8228910728910729

In [30]:
# This should be the same as above!

avg.score(X_te_ohe, y_test)

0.828030954428203

### Weighted Averaging

> Even if the vote is 50-50, you'd probably side with the "smart" ones more

This meta-estimator is not as good as one of our base estimators, so in this case the averaging did not work very well. Realizing that the decision tree is performing better than the logistic regression and the k-nearest-neighbors model, however, we might decide to build a meta-estimator by calculating a **weighted average** of the base estimators' predictions. And we can weight, or bias, this estimator in favor of the best-performing base estimator. Suppose we weight the tree 40%, the knn model 20%, and the logistic regression 40%:

In [31]:
weighted_preds = sum([0.4 * lr.predict(X_te_ohe), 0.2 * knn.predict(X_te_ohe),
                     0.4 * rt.predict(X_te_ohe)])

Now we can evaluate this new meta-estimator:

In [32]:
r2_score(y_test, weighted_preds)

0.2046356746045599

#### Weighted Averaging with the VotingClassifier

In [33]:
w_avg = VotingClassifier(estimators=[
    ('lr', lr),
    ('knn', knn),
    ('rt', rt)],
    weights=[0.4, 0.2, 0.4])
w_avg.fit(X_tr_ohe, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression()),
                             ('knn', KNeighborsClassifier()),
                             ('rt', DecisionTreeClassifier(random_state=42))],
                 weights=[0.4, 0.2, 0.4])

In [34]:
scores = cross_val_score(estimator=w_avg, X=X_tr_ohe,
                        y=y_train, cv=5)
scores

array([0.81756757, 0.82616708, 0.82289107, 0.83210483, 0.82289107])

In [35]:
np.median(scores)

0.8228910728910729

In [36]:
# This should be the same as above!

w_avg.score(X_te_ohe, y_test)

0.828030954428203

# Bagging

A single decision tree will often overfit your training data. Let's see if we have evidence of that in the current case:

In [37]:
rt.score(X_tr_ohe, y_train)

0.8329238329238329

<details>
    <summary><b>🧠 Knowledge Check</b>: What is this score? And why is it nearly equal to 1?</summary>
    <br/>
    <quote>
    This nearly perfect score on the training data is already evidence of model overfitting. There are steps one can take to help with this, like limiting the "depth" of the nodes. And of course we can use cross-validation to get a more honest estimate of model quality
    </quote>
</details>




In [38]:
scores = cross_val_score(estimator=rt, X=X_tr_ohe,
                y=y_train, cv=5)
scores

array([0.81613432, 0.82166257, 0.82104832, 0.82964783, 0.81981982])

In [39]:
np.median(scores)

0.821048321048321

In [40]:
rt.score(X_te_ohe, y_test)

0.8250829136469722

But it's often better to do something else: Plant another tree!

Of course, if a second tree is going to be of any value, it has to be *different from* the first. Here's a good algorithm for achieving that:

## Bagging Algorithm

- Take a sample of your X_train and fit a decision tree to it.
- Replace the first batch of data and repeat.
- When you've got as many trees as you like, make use of all your individual trees' predictions to come up with some holistic prediction. 
    - (Most obviously, we could take the average of our predictions, but there are other methods we might try.)

* Because we're resampling our data with replacement, we're *bootstrapping*.
  --pasteing is bootstrap WITHOUT replacement (ie replace=False)
* Because we're making use of our many samples' predictions, we're *aggregating*.
* Because we're bootstrapping and aggregating all in the same algorithm, we're *bagging*.

## Back to the Example Data

In [41]:
# Instatiate a BaggingRegessor

bag = BaggingClassifier(n_estimators=100,
                       verbose=1,
                       random_state=1)

In [42]:
# Fit it

bag.fit(X_tr_ohe, y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    4.2s finished


BaggingClassifier(n_estimators=100, random_state=1, verbose=1)

In [43]:
# Cross-validation

scores = cross_val_score(estimator=bag, X=X_tr_ohe,
               y=y_train, cv=5)
scores

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.4s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.9s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.0s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_j

array([0.81572482, 0.82268632, 0.82043407, 0.82678133, 0.81941032])

In [44]:
np.median(scores)

0.8204340704340705

In [45]:
# Score on test

bag.score(X_te_ohe, y_test)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.3s finished


0.8241002333865618

### Change the base estimator

In [46]:
bag = BaggingClassifier(random_state=1,
                      base_estimator=KNeighborsClassifier(3),
                       n_estimators=4)

In [47]:
bag.fit(X_tr_ohe, y_train)

BaggingClassifier(base_estimator=KNeighborsClassifier(n_neighbors=3),
                  n_estimators=4, random_state=1)

In [48]:
bag.score(X_te_ohe, y_test)

0.804692298243459

# Fitting a Random Forest

## An Aside Story - Bananas 🍌

Banana trees can be susceptible to [Panama's disease](https://en.wikipedia.org/wiki/Panama_disease)

![Many individual yellow bananas](images/bananas.jpg)

They're all clones!

Similarly, all the Decision Trees will be the same if given the same data! (A clone!!!)

## The Goods & The Bads

**The Goods**

- Super friend! 
- High performance 
    + low variance
- Transparent
    + inherited from Decision Trees
    

**The Bads**

- We got so many trees to plant...
- Computationally expensive
- Memory
    + all trees stored in memory
    + think back to k-Nearest Neighbors

### Breed variety of trees

Let's add an extra layer of randomization: Instead of using *all* the features of my model to optimize a branch at each node, I'll just choose a subset of my features.

That's the essence of a random forest model. Note that there are now **two** levels of random sampling happening: To build a new tree, I'll be taking only some of my data points; and at any branching point in a tree, I'll be using only some of my features to determine the split.

#### Steps:

1. Save a portion of data for validation (**out-of-bag**), the rest for training (**bag**)
2. The data for training (**bag**) is then split up by randomly selecting predictors
3. Grow/train your tree with the training data using just those features
4. Use our validation set (**out-of-bag**), take out the columns used in our tree from the previous step, and predict using the tree & this *out-of-bag* data
5. Compare on how well the tree did *out-of-bag error*
6. Repeat to make new trees and use the result to "vote" for the final decision

## Back to the Example Data

> Here's the [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier) on `RandomForestClassifier`

Default is 100

In [49]:
# Instantiate a RandomForestClassifier

rfr = RandomForestClassifier(max_features='sqrt',
                            max_samples=0.5,
                            random_state=1)

In [50]:
# Fit it

rfr.fit(X_tr_ohe, y_train)

RandomForestClassifier(max_features='sqrt', max_samples=0.5, random_state=1)

In [51]:
# Cross-validation

scores = cross_val_score(estimator=rfr, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.81838657, 0.82186732, 0.82104832, 0.82903358, 0.82125307])

In [52]:
np.median(scores)

0.8212530712530712

In [53]:
# Score on test

score = rfr.score(X_te_ohe, y_test)
score

0.8249600786144208

In [54]:
X_te_ohe.columns

Index(['x0_11th', 'x0_12th', 'x0_1st-4th', 'x0_5th-6th', 'x0_7th-8th',
       'x0_9th', 'x0_Assoc-acdm', 'x0_Assoc-voc', 'x0_Bachelors',
       'x0_Doctorate', 'x0_HS-grad', 'x0_Masters', 'x0_Preschool',
       'x0_Prof-school', 'x0_Some-college', 'x1_Adm-clerical',
       'x1_Armed-Forces', 'x1_Craft-repair', 'x1_Exec-managerial',
       'x1_Farming-fishing', 'x1_Handlers-cleaners', 'x1_Machine-op-inspct',
       'x1_Other-service', 'x1_Priv-house-serv', 'x1_Prof-specialty',
       'x1_Protective-serv', 'x1_Sales', 'x1_Tech-support',
       'x1_Transport-moving', 'x2_Not-in-family', 'x2_Other-relative',
       'x2_Own-child', 'x2_Unmarried', 'x2_Wife', 'x3_Male'],
      dtype='object')

## Cool Features of Random Forests

There are some extra investigations we can do with random forests since they're built of decision trees.

> **NOTE**
>
> Not all of these are _specific_ to random forests and can be applied to other (ensemble) models

### Investigate Your Forest 🌲🌲👀🌲🌲

We can check out our trained estimators after training the ensemble. This isn't necessarily unique to random forests, but since the base model is always a decision tree we can really investigate how the model is working!

In [55]:
model_estimators = rfr.estimators_ 
print(len(model_estimators))
model_estimators

100


[DecisionTreeClassifier(max_features='sqrt', random_state=1791095845),
 DecisionTreeClassifier(max_features='sqrt', random_state=2135392491),
 DecisionTreeClassifier(max_features='sqrt', random_state=946286476),
 DecisionTreeClassifier(max_features='sqrt', random_state=1857819720),
 DecisionTreeClassifier(max_features='sqrt', random_state=491263),
 DecisionTreeClassifier(max_features='sqrt', random_state=550290313),
 DecisionTreeClassifier(max_features='sqrt', random_state=1298508491),
 DecisionTreeClassifier(max_features='sqrt', random_state=2143362693),
 DecisionTreeClassifier(max_features='sqrt', random_state=630311759),
 DecisionTreeClassifier(max_features='sqrt', random_state=1013994432),
 DecisionTreeClassifier(max_features='sqrt', random_state=396591248),
 DecisionTreeClassifier(max_features='sqrt', random_state=1703301249),
 DecisionTreeClassifier(max_features='sqrt', random_state=799981516),
 DecisionTreeClassifier(max_features='sqrt', random_state=1666063943),
 DecisionTreeCl

In [56]:
print(f'Overall model\'s score was {score:.3f}')
print('='*70)

for model in model_estimators[:5]:
    display(model)
    model_score = model.score(X_te_ohe, y_test)
    print(f'\tModel gave score of {model_score:.3f}')

Overall model's score was 0.825


DecisionTreeClassifier(max_features='sqrt', random_state=1791095845)

	Model gave score of 0.823


DecisionTreeClassifier(max_features='sqrt', random_state=2135392491)

	Model gave score of 0.822


DecisionTreeClassifier(max_features='sqrt', random_state=946286476)

	Model gave score of 0.819


DecisionTreeClassifier(max_features='sqrt', random_state=1857819720)

	Model gave score of 0.822


DecisionTreeClassifier(max_features='sqrt', random_state=491263)

	Model gave score of 0.821


### Feature Importance

We can use [`.feature_importances_`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#sklearn.ensemble.RandomForestClassifier.feature_importances_) property of the trained model to get an idea of what features mattered the most

In [57]:
feat_import = {name: score 
                   for name, score 
                       in zip(X_te_ohe.columns, rfr.feature_importances_)
}
feat_import

{'x0_11th': 0.00980712490911537,
 'x0_12th': 0.0038737852216593816,
 'x0_1st-4th': 0.0021472312633547884,
 'x0_5th-6th': 0.003634926552043488,
 'x0_7th-8th': 0.007066801422009459,
 'x0_9th': 0.006244667656806083,
 'x0_Assoc-acdm': 0.010863954851914798,
 'x0_Assoc-voc': 0.010229604641031053,
 'x0_Bachelors': 0.0635689750402614,
 'x0_Doctorate': 0.022259610336353458,
 'x0_HS-grad': 0.02334469334612589,
 'x0_Masters': 0.051159117468887814,
 'x0_Preschool': 0.00037664419884751596,
 'x0_Prof-school': 0.032820840422392146,
 'x0_Some-college': 0.016303429754082506,
 'x1_Adm-clerical': 0.010753565590176829,
 'x1_Armed-Forces': 5.7819127477563116e-05,
 'x1_Craft-repair': 0.009424234231434946,
 'x1_Exec-managerial': 0.08287174941777982,
 'x1_Farming-fishing': 0.00898163107923625,
 'x1_Handlers-cleaners': 0.009905128863746221,
 'x1_Machine-op-inspct': 0.007786686690077609,
 'x1_Other-service': 0.026205708447500413,
 'x1_Priv-house-serv': 0.0007005907744311382,
 'x1_Prof-specialty': 0.063558502698

## Extremely Randomized Trees (Extra Trees)

Sometimes we might want even one more bit of randomization. Instead of always choosing the *optimal* branching path, we might just choose a branching path at random. If we're doing that, then we've got extremely randomized trees.

There are now **three** levels of randomization: sampling of data, sampling of features, and random selection of branching paths.

In [58]:
# Instantiate an ExtraTreesRegressor

etr = ExtraTreesClassifier(max_features='sqrt',
                         max_samples=0.5,
                         bootstrap=True,
                         random_state=1)

In [59]:
# Fit it

etr.fit(X_tr_ohe, y_train)

ExtraTreesClassifier(bootstrap=True, max_features='sqrt', max_samples=0.5,
                     random_state=1)

In [60]:
# Cross-validation

scores = cross_val_score(estimator=etr, X=X_tr_ohe,
               y=y_train, cv=5)
scores

array([0.81777232, 0.82104832, 0.82186732, 0.82944308, 0.82166257])

In [61]:
np.median(scores)

0.8216625716625716

In [62]:
# Score on test

etr.score(X_te_ohe, y_test)

0.8245915735167669